### ISSUE TITLE
Screenshot issue

### ISSUE THREAD

**Issue by pantsumit** [SubhamTyagi/loco-hack#10]
HELLO DUDE PLEASE TELL THAT HOW TO SETUP SCREENSHOT SIZE IN SCRIPT PL. IT IS BEEN TOO CONFUSING

**Comment by SubhamTyagi** [comment]
## STEP TO SET CO-ORDINATES

 - Take a screenshot of question with answers
 - Go to your phone Settings >Developer option>Pointer location
 - Switch on Pointer location 
 - Get both(i.e. top and bottom) co-ordinates of question and all option 
 - set these values in bot2.py file

**Comment by pantsumit** [comment]
thanks dude😍😍

**Comment by Hite360** [comment]
Please Help image Object unsupported
