### ISSUE TITLE
ERROR IN SCREEN.PNG

### ISSUE THREAD

**Issue by pantsumit** [SubhamTyagi/loco-hack#11]
hey subham as i opening bot.py and running it in live it is showing me a error:

Press l for live game, s  to run against sample questions or q for quit:
l
[  ==] Reading screenTraceback (most recent call last):
  File "bot.py", line 249, in <module>
    get_points_live(False)
  File "bot.py", line 225, in get_points_live
    question, options = take_screenshot_and_get_text(demo)
  File "bot.py", line 163, in take_screenshot_and_get_text
    i = Image.open(screenshot_file)
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'screen.png'

i'm running yr script in kali linux 2018 please suggest something

**Comment by SubhamTyagi** [comment]
Use device and connect it with data cable
