### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by pkmuz1** [SubhamTyagi/loco-hack#2]
please write a tutorial about this

i got urllib error

**Comment by SubhamTyagi** [comment]
which version of python you are using
use python27 if you have some error send screenshot
and also check i updated the script

**Comment by pkmuz1** [comment]
python 3.6.5 , and using updated script

**Comment by SubhamTyagi** [comment]
Change all instance of urllib2 to urllib for python 3.*

**Comment by pkmuz1** [comment]
![2018-05-21_173849ssssssssssss](https://user-images.githubusercontent.com/31066286/40306888-ff0a294a-5d1d-11e8-976e-5cb6242a9888.jpg)


after installing python 2.7

**Comment by SubhamTyagi** [comment]
Install tesseract and add tesseract.exe containing folder to your path

Download tesseract installer from https://github.com/tesseract-ocr/tesseract/wiki

**Comment by SubhamTyagi** [comment]
And update you bot.py file

**Comment by SubhamTyagi** [comment]
As i see your files are not updated , update your bot.py file from repo

**Comment by pkmuz1** [comment]
everything is working fine but it takes 20+ sec to answer

**Comment by SubhamTyagi** [comment]
I am working for it
