### ISSUE TITLE
Sir, I press l it show error----- IOError: cannot identify image file 'screen.png'         ,python2.7,ubuntu18

### ISSUE THREAD

**Issue by ks4ghz** [SubhamTyagi/loco-hack#3]
![screenshot from 2018-05-30 22-31-06](https://user-images.githubusercontent.com/39774329/40735627-4656dc02-6459-11e8-88c8-f68e4875b0aa.png)

**Comment by SubhamTyagi** [comment]
Is you are working with LIVE game?


It seems that  ```adb```  is not taking a screenshot. Your phone is not properly connect with adb.

Send a full screenshot.
 
Well i am working on Android phone app for loco hack, in some next few days i publish it on GitHub.![](https://i.imgur.com/v1kT8K2.png)

**Comment by ks4ghz** [comment]
great job....

adb installed correctly, screen.png file inavlid

ks4ghz@ks4ghz-SVE14112ENB:~/Desktop/loco-hack-master$ python bot.py

Press l for live game, s  to run against sample questions or q for quit:
l
[   =] Reading screenAndroid Debug Bridge version 1.0.29

 -d                            - directs command to the only connected USB device
                                 returns an error if more than one USB device is present.
 -e                            - directs command to the only running emulator.
                                 returns an error if more than one emulator is running.
 -s <serial number>            - directs command to the USB device or emulator with
                                 the given serial number. Overrides ANDROID_SERIAL
                                 environment variable.
 -p <product name or path>     - simple product name like 'sooner', or
                                 a relative/absolute path to a product
                                 out directory like 'out/target/product/sooner'.
                                 If -p is not specified, the ANDROID_PRODUCT_OUT
                                 environment variable is used, which must
                                 be an absolute path.
 devices                       - list all connected devices
 connect <host>[:<port>]       - connect to a device via TCP/IP
                                 Port 5555 is used by default if no port number is specified.
 disconnect [<host>[:<port>]]  - disconnect from a TCP/IP device.
                                 Port 5555 is used by default if no port number is specified.
                                 Using this command with no additional arguments
                                 will disconnect from all connected TCP/IP devices.

device commands:
  adb push <local> <remote>    - copy file/dir to device
  adb pull <remote> [<local>]  - copy file/dir from device
  adb sync [ <directory> ]     - copy host->device only if changed
                                 (-l means list but don't copy)
                                 (see 'adb help all')
  adb shell                    - run remote shell interactively
  adb shell <command>          - run remote shell command
  adb emu <command>            - run emulator console command
  adb logcat [ <filter-spec> ] - View device log
  adb forward <local> <remote> - forward socket connections
                                 forward specs are one of: 
                                   tcp:<port>
                                   localabstract:<unix domain socket name>
                                   localreserved:<unix domain socket name>
                                   localfilesystem:<unix domain socket name>
                                   dev:<character device name>
                                   jdwp:<process pid> (remote only)
  adb jdwp                     - list PIDs of processes hosting a JDWP transport
  adb install [-l] [-r] [-s] <file> - push this package file to the device and install it
                                 ('-l' means forward-lock the app)
                                 ('-r' means reinstall the app, keeping its data)
                                 ('-s' means install on SD card instead of internal storage)
  adb uninstall [-k] <package> - remove this app package from the device
                                 ('-k' means keep the data and cache directories)
  adb bugreport                - return all information from the device
                                 that should be included in a bug report.

  adb backup [-f <file>] [-apk|-noapk] [-shared|-noshared] [-all] [-system|-nosystem] [<packages...>]
                               - write an archive of the device's data to <file>.
                                 If no -f option is supplied then the data is written
                                 to "backup.ab" in the current directory.
                                 (-apk|-noapk enable/disable backup of the .apks themselves
                                    in the archive; the default is noapk.)
                                 (-shared|-noshared enable/disable backup of the device's
                                    shared storage / SD card contents; the default is noshared.)
                                 (-all means to back up all installed applications)
                                 (-system|-nosystem toggles whether -all automatically includes
                                    system applications; the default is to include system apps)
                                 (<packages...> is the list of applications to be backed up.  If
                                    the -all or -shared flags are passed, then the package
                                    list is optional.  Applications explicitly given on the
                                    command line will be included even if -nosystem would
                                    ordinarily cause them to be omitted.)

  adb restore <file>           - restore device contents from the <file> backup archive

  adb help                     - show this help message
  adb version                  - show version num

scripting:
  adb wait-for-device          - block until device is online
  adb start-server             - ensure that there is a server running
  adb kill-server              - kill the server if it is running
  adb get-state                - prints: offline | bootloader | device
  adb get-serialno             - prints: <serial-number>
  adb status-window            - continuously print device status for a specified device
  adb remount                  - remounts the /system partition on the device read-write
  adb reboot [bootloader|recovery] - reboots the device, optionally into the bootloader or recovery program
  adb reboot-bootloader        - reboots the device into the bootloader
  adb root                     - restarts the adbd daemon with root permissions
  adb usb                      - restarts the adbd daemon listening on USB
  adb tcpip <port>             - restarts the adbd daemon listening on TCP on the specified port
networking:
  adb ppp <tty> [parameters]   - Run PPP over USB.
 Note: you should not automatically start a PPP connection.
 <tty> refers to the tty for PPP stream. Eg. dev:/dev/omap_csmi_tty1
 [parameters] - Eg. defaultroute debug dump local notty usepeerdns

adb sync notes: adb sync [ <directory> ]
  <localdir> can be interpreted in several ways:

  - If <directory> is not specified, both /system and /data partitions will be updated.

  - If it is "system" or "data", only the corresponding partition
    is updated.

environmental variables:
  ADB_TRACE                    - Print debug information. A comma separated list of the following values
                                 1 or all, adb, sockets, packets, rwx, usb, sync, sysdeps, transport, jdwp
  ANDROID_SERIAL               - The serial number to connect to. -s takes priority over this if given.
  ANDROID_LOG_TAGS             - When used with the logcat option, only these debug tags are printed.
Traceback (most recent call last):
  File "bot.py", line 249, in <module>
    get_points_live(False)
  File "bot.py", line 225, in get_points_live
    question, options = take_screenshot_and_get_text(demo)
  File "bot.py", line 163, in take_screenshot_and_get_text
    i = Image.open(screenshot_file)
  File "/home/ks4ghz/.local/lib/python2.7/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'screen.png'
ks4ghz@ks4ghz-SVE14112ENB:~/Desktop/loco-hack-master$

**Comment by SubhamTyagi** [comment]
is you enabled debugging mode in Developers settings?
if not go to settings>About Phone>
tap Build number 7 times your developer option is enabled in settings. face to developer settings 
enable USB Debuging and Developers option.

**Comment by SubhamTyagi** [comment]
and see i updated the repo

**Comment by ks4ghz** [comment]
debugging enabled

**Comment by ks4ghz** [comment]
bot 2 error 
![screenshot from 2018-05-31 11-20-42](https://user-images.githubusercontent.com/39774329/40763980-b81fcbbc-64c4-11e8-9527-d894dfbcbea1.png)

**Comment by SubhamTyagi** [comment]
this is not a error it only works when live game but 
 now i again updated bot2.py when you are run against live quiz uncomment line `128`
as `demo = False`

**Comment by ks4ghz** [comment]
ope loco demo play in loco app.
show the same error
screen.png correpted

**Comment by SubhamTyagi** [comment]
Download new screen.png file or clone repo

**Comment by ks4ghz** [comment]
error again

![screenshot from 2018-05-31 20-38-46](https://user-images.githubusercontent.com/39774329/40790474-ac59ef3a-6512-11e8-898e-b827b7c1a483.png)

**Comment by SubhamTyagi** [comment]
You have not installed tesseract

Install it using
```
sudo apt-get install tesseract-ocr

```  or as written in README file

**Comment by ks4ghz** [comment]
tnx..... its working..

**Comment by SubhamTyagi** [comment]
I will Publish a Android app for this on GitHub. 
On[Loco hack Android app](https://github.com/SubhamTyagi/loco-answers)
