### ISSUE TITLE
answering take more than 10 s

### ISSUE THREAD

**Issue by ks4ghz** [SubhamTyagi/loco-hack#4]

**Comment by SubhamTyagi** [comment]
Which bot ? bot.py or bot2.py.
It is not a bug. Speed of bot is  also depends upon system speed, network speed and somewhat on Algorithm.

Second bot i.e. _bot2.py_  take less than 5 second to answer on my system. But first bot _bot.py_ take some more time , so a new version of 
```
Bot.py
```  will be uploaded to GitHub soon 

Thanks.
