### ISSUE TITLE
Doesn't work  , Creates a lot of errors

### ISSUE THREAD

**Issue by fineanmol** [SubhamTyagi/loco-hack#5]
get_screen_shot(demo)
[0m[0m[0m[0m[0m[0m  File "C:\Users\Anmol Agarwal\Desktop\bot2.py", line 73, in get_screen_shot
    i = Image.open(screenfile)
[0m[0m[0m[0m[0m[0m  File "F:\Program\Python36\lib\site-packages\PIL\Image.py", line 2548, in open
    fp = builtins.open(filename, "rb")
[0m[0m[0m[0m[0m[0mFileNotFoundError: [Errno 2] No such file or directory: 'screendemo.png'
[0m[0m[0m[0m[0m[0m

**Comment by SubhamTyagi** [comment]
Clone repo again

**Comment by SubhamTyagi** [comment]
first read README file then run script
