### ISSUE TITLE
sir how to coorect the resalution of  image..

### ISSUE THREAD

**Issue by ks4ghz** [SubhamTyagi/loco-hack#6]
images are disorderd
![a](https://user-images.githubusercontent.com/39774329/40855683-d5f13480-65f2-11e8-8a1f-bfab20950a76.png)
![b](https://user-images.githubusercontent.com/39774329/40855685-d76b1d30-65f2-11e8-8fdb-c74e6baa39b7.png)
![c](https://user-images.githubusercontent.com/39774329/40855686-d9b4ffe8-65f2-11e8-9586-1906867360a5.png)
![quest](https://user-images.githubusercontent.com/39774329/40855693-dbe61e28-65f2-11e8-851d-69a7f5ff504f.png)

**Comment by SubhamTyagi** [comment]
Change co-ordinate  according to your phone screen size in bot

**Comment by SubhamTyagi** [comment]
https://github.com/SubhamTyagi/loco-answers/releases


Install this

**Comment by saff12** [comment]
New loco hack is not working in loco game
Any solution ??

**Comment by nsptraj** [comment]
Sir please make a app for all trivia apps. your app is great.

**Comment by nsptraj** [comment]
I want to ask something .trivia helper app works on every mobile but not in my mobile .it show no text on screen.is that app not reading text on my screen.please help me .sir
